# Generated by Django 5.0.3 on 2024-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leavetype',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejectionreason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
