# Generated by Django 5.0.3 on 2024-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_leaverequest_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leavetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
