# Generated by Django 5.0.3 on 2024-07-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_rename_profile_employee_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='requested_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
