# Generated by Django 5.0.3 on 2024-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_department_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='login',
            name='first_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='is_staff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
