# Generated by Django 5.0.3 on 2024-08-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_login_date_joined_login_email_login_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
