# Generated by Django 5.0.3 on 2024-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_assign',
            name='task_status',
            field=models.CharField(blank=True, default='not started', max_length=255, null=True),
        ),
    ]
