# Generated by Django 5.0.3 on 2024-08-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_task_id_task_assign_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_assign',
            old_name='task',
            new_name='task_id',
        ),
    ]
