# Generated by Django 5.0.3 on 2024-08-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_rename_task_task_assign_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_assign',
            old_name='task_id',
            new_name='task',
        ),
    ]
